# Shared configuration for all ERP backend services
spring:
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.SnakeCasePhysicalNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

# Supabase Configuration
supabase:
  enabled: true
  url: ${SUPABASE_URL}
  anon-key: ${SUPABASE_ANON_KEY}
  db:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}

# Audit Configuration
audit:
  enabled: ${AUDIT_LOGGING:true}
  async: true
  retention-days: 365

# Validation Configuration
validation:
  email:
    enabled: true
  phone:
    enabled: true
  employee-id:
    enabled: true
    pattern: "^[A-Za-z0-9]{3,20}$"

# Security Configuration
security:
  jwt:
    secret: ${ERP_JWT_SECRET:your-jwt-secret-key-change-in-production}
    expiration: ${ERP_SESSION_TIMEOUT:3600}

# Logging Configuration
logging:
  level:
    com.unifiederp.shared: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_PARAM_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

# Cross-Module Integration
integration:
  events:
    enabled: ${CROSS_MODULE_EVENTS:true}
  notifications:
    enabled: ${REAL_TIME_NOTIFICATIONS:true}

---
# Development Profile
spring:
  config:
    activate:
      on-profile: development

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.unifiederp.shared: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

audit:
  enabled: false

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.unifiederp.shared: WARN
    org.hibernate.SQL: WARN